import { Event } from './Event';
import { Header } from './Header';
import { useEffect, useRef } from 'react';

export function DynamicBoard() {

  const keyMarkets = ['Spread', 'Money Line', 'Total Points'];
  const title = 'WNBA'; 

  const events = [
    {
        id: 1,
        teamA: 'Atlanta Dream',
        teamB: 'Connecticut Sun',
        time: 'Today 7:00pm',
        spreadA: '+4.5',
        spreadB: '-4.5',
        moneyLineA: '+250',
        moneyLineB: '-300',
        totalPoints: 'O 155.0 / U 155.0',
        inPlay: false,
    },
    {
        id: 2,
        teamA: 'Dallas Wings',
        teamB: 'Chicago Sky',
        time: 'Tomorrow 8:30pm',
        spreadA: '+2.0',
        spreadB: '-2.0',
        moneyLineA: '+180',
        moneyLineB: '-220',
        totalPoints: 'O 162.0 / U 162.0',
        inPlay: false,
    },
    {
        id: 3,
        teamA: 'Minnesota Lynx',
        teamB: 'New York Liberty',
        time: 'Today 6:00pm',
        spreadA: '+7.0',
        spreadB: '-7.0',
        moneyLineA: '+400',
        moneyLineB: '-600',
        totalPoints: 'O 158.5 / U 158.5',
        inPlay: false,
    },
    {
        id: 4,
        teamA: 'Phoenix Mercury',
        teamB: 'Las Vegas Aces',
        time: 'Tomorrow 9:00pm',
        spreadA: '+3.5',
        spreadB: '-3.5',
        moneyLineA: '+150',
        moneyLineB: '-175',
        totalPoints: 'O 164.0 / U 164.0',
        inPlay: false,
        score: { A: 80, B: 88 },
    },
    {
        id: 5,
        teamA: 'Seattle Storm',
        teamB: 'Washington Mystics',
        time: 'Today 8:00pm',
        spreadA: '-5.5',
        spreadB: '+5.5',
        moneyLineA: '-150',
        moneyLineB: '+130',
        totalPoints: 'O 167.0 / U 167.0',
        inPlay: false,
    },
    {
        id: 6,
        teamA: 'Atlanta Dream',
        teamB: 'Connecticut Sun',
        time: 'Today 7:00pm',
        spreadA: '+4.5',
        spreadB: '-4.5',
        moneyLineA: '+250',
        moneyLineB: '-300',
        totalPoints: 'O 155.0 / U 155.0',
        inPlay: false,
    },
    {
        id: 7,
        teamA: 'Dallas Wings',
        teamB: 'Chicago Sky',
        time: 'Tomorrow 8:30pm',
        spreadA: '+2.0',
        spreadB: '-2.0',
        moneyLineA: '+180',
        moneyLineB: '-220',
        totalPoints: 'O 162.0 / U 162.0',
        inPlay: false,
        score: { A: 78, B: 80 },
    },
    {
        id: 8,
        teamA: 'Minnesota Lynx',
        teamB: 'New York Liberty',
        time: 'Today 6:00pm',
        spreadA: '+7.0',
        spreadB: '-7.0',
        moneyLineA: '+400',
        moneyLineB: '-600',
        totalPoints: 'O 158.5 / U 158.5',
        inPlay: false,
    },
    {
        id: 9,
        teamA: 'Phoenix Mercury',
        teamB: 'Las Vegas Aces',
        time: 'Tomorrow 9:00pm',
        spreadA: '+3.5',
        spreadB: '-3.5',
        moneyLineA: '+150',
        moneyLineB: '-175',
        totalPoints: 'O 164.0 / U 164.0',
        inPlay: false,
        score: { A: 85, B: 90 },
    },
    {
        id: 10,
        teamA: 'Seattle Storm',
        teamB: 'Washington Mystics',
        time: 'Today 8:00pm',
        spreadA: '-5.5',
        spreadB: '+5.5',
        moneyLineA: '-150',
        moneyLineB: '+130',
        totalPoints: 'O 167.0 / U 167.0',
        inPlay: false,
    },
    {
        id: 11,
        teamA: 'Atlanta Dream',
        teamB: 'Connecticut Sun',
        time: 'Tomorrow 7:00pm',
        spreadA: '+4.5',
        spreadB: '-4.5',
        moneyLineA: '+250',
        moneyLineB: '-300',
        totalPoints: 'O 155.0 / U 155.0',
        inPlay: false,
    },
    {
        id: 12,
        teamA: 'Dallas Wings',
        teamB: 'Chicago Sky',
        time: 'Today 8:30pm',
        spreadA: '+2.0',
        spreadB: '-2.0',
        moneyLineA: '+180',
        moneyLineB: '-220',
        totalPoints: 'O 162.0 / U 162.0',
        inPlay: false,
        score: { A: 75, B: 82 },
    },
    {
        id: 13,
        teamA: 'Minnesota Lynx',
        teamB: 'New York Liberty',
        time: 'Tomorrow 6:00pm',
        spreadA: '+7.0',
        spreadB: '-7.0',
        moneyLineA: '+400',
        moneyLineB: '-600',
        totalPoints: 'O 158.5 / U 158.5',
        inPlay: false,
    },
    {
        id: 14,
        teamA: 'Phoenix Mercury',
        teamB: 'Las Vegas Aces',
        time: 'Today 9:00pm',
        spreadA: '+3.5',
        spreadB: '-3.5',
        moneyLineA: '+150',
        moneyLineB: '-175',
        totalPoints: 'O 164.0 / U 164.0',
        inPlay: false,
        score: { A: 89, B: 92 },
    },
    {
        id: 15,
        teamA: 'Seattle Storm',
        teamB: 'Washington Mystics',
        time: 'Tomorrow 8:00pm',
        spreadA: '-5.5',
        spreadB: '+5.5',
        moneyLineA: '-150',
        moneyLineB: '+130',
        totalPoints: 'O 167.0 / U 167.0',
        inPlay: false,
    },
    {
        id: 16,
        teamA: 'Atlanta Dream',
        teamB: 'Los Angeles Sparks',
        time: 'Today 7:00pm',
        spreadA: '+6.5',
        spreadB: '-6.5',
        moneyLineA: '+300',
        moneyLineB: '-400',
        totalPoints: 'O 159.0 / U 159.0',
        inPlay: false,
    },
    {
        id: 17,
        teamA: 'Chicago Sky',
        teamB: 'Indiana Fever',
        time: 'Tomorrow 8:30pm',
        spreadA: '-3.0',
        spreadB: '+3.0',
        moneyLineA: '-160',
        moneyLineB: '+140',
        totalPoints: 'O 166.0 / U 166.0',
        inPlay: false,
    },
    {
        id: 18,
        teamA: 'New York Liberty',
        teamB: 'Las Vegas Aces',
        time: 'Today 6:00pm',
        spreadA: '+2.5',
        spreadB: '-2.5',
        moneyLineA: '+200',
        moneyLineB: '-240',
        totalPoints: 'O 164.5 / U 164.5',
        inPlay: false,
    },
    {
        id: 19,
        teamA: 'Phoenix Mercury',
        teamB: 'Washington Mystics',
        time: 'Tomorrow 9:00pm',
        spreadA: '-1.5',
        spreadB: '+1.5',
        moneyLineA: '-120',
        moneyLineB: '+100',
        totalPoints: 'O 160.0 / U 160.0',
        inPlay: false,
        score: { A: 84, B: 81 },
    },
    {
        id: 20,
        teamA: 'Seattle Storm',
        teamB: 'Atlanta Dream',
        time: 'Today 8:00pm',
        spreadA: '-4.0',
        spreadB: '+4.0',
        moneyLineA: '-140',
        moneyLineB: '+120',
        totalPoints: 'O 165.0 / U 165.0',
        inPlay: false,
    },
    {
          id: 21,
          teamA: 'Los Angeles Sparks',
          teamB: 'Dallas Wings',
          time: 'Tomorrow 7:00pm',
          spreadA: '-2.5',
          spreadB: '+2.5',
          moneyLineA: '-130',
          moneyLineB: '+110',
          totalPoints: 'O 162.5 / U 162.5',
          inPlay: false,
      },
      {
          id: 22,
          teamA: 'Minnesota Lynx',
          teamB: 'Chicago Sky',
          time: 'Today 6:30pm',
          spreadA: '+5.0',
          spreadB: '-5.0',
          moneyLineA: '+220',
          moneyLineB: '-260',
          totalPoints: 'O 157.0 / U 157.0',
          inPlay: false,
      },
      {
          id: 23,
          teamA: 'New York Liberty',
          teamB: 'Atlanta Dream',
          time: 'Tomorrow 8:00pm',
          spreadA: '-3.5',
          spreadB: '+3.5',
          moneyLineA: '-145',
          moneyLineB: '+125',
          totalPoints: 'O 163.0 / U 163.0',
          inPlay: false,
          score: { A: 90, B: 86 },
      },
      {
          id: 24,
          teamA: 'Phoenix Mercury',
          teamB: 'Seattle Storm',
          time: 'Today 9:00pm',
          spreadA: '+4.0',
          spreadB: '-4.0',
          moneyLineA: '+210',
          moneyLineB: '-250',
          totalPoints: 'O 161.0 / U 161.0',
          inPlay: false,
      },
      {
          id: 25,
          teamA: 'Washington Mystics',
          teamB: 'Los Angeles Sparks',
          time: 'Tomorrow 7:00pm',
          spreadA: '+3.0',
          spreadB: '-3.0',
          moneyLineA: '+180',
          moneyLineB: '-215',
          totalPoints: 'O 165.5 / U 165.5',
          inPlay: false,
      },
      {
          id: 26,
          teamA: 'Dallas Wings',
          teamB: 'Minnesota Lynx',
          time: 'Today 6:00pm',
          spreadA: '-2.0',
          spreadB: '+2.0',
          moneyLineA: '-135',
          moneyLineB: '+115',
          totalPoints: 'O 159.5 / U 159.5',
          inPlay: false,
      },
      {
          id: 27,
          teamA: 'Chicago Sky',
          teamB: 'New York Liberty',
          time: 'Tomorrow 9:00pm',
          spreadA: '+1.5',
          spreadB: '-1.5',
          moneyLineA: '+190',
          moneyLineB: '-225',
          totalPoints: 'O 162.0 / U 162.0',
          inPlay: false,
      },
      {
          id: 28,
          teamA: 'Las Vegas Aces',
          teamB: 'Phoenix Mercury',
          time: 'Today 7:30pm',
          spreadA: '-6.0',
          spreadB: '+6.0',
          moneyLineA: '-160',
          moneyLineB: '+140',
          totalPoints: 'O 168.0 / U 168.0',
          inPlay: false,
          score: { A: 95, B: 80 },
      },
      {
          id: 29,
          teamA: 'Washington Mystics',
          teamB: 'Seattle Storm',
          time: 'Tomorrow 8:00pm',
          spreadA: '+5.5',
          spreadB: '-5.5',
          moneyLineA: '+240',
          moneyLineB: '-300',
          totalPoints: 'O 159.0 / U 159.0',
          inPlay: false,
      },
      {
          id: 30,
          teamA: 'Los Angeles Sparks',
          teamB: 'Atlanta Dream',
          time: 'Today 7:00pm',
          spreadA: '-4.0',
          spreadB: '+4.0',
          moneyLineA: '-150',
          moneyLineB: '+130',
          totalPoints: 'O 164.0 / U 164.0',
          inPlay: false,
          score: { A: 87, B: 84 },
      },

        {
            id: 31,
            teamA: 'Orlando Pride',
            teamB: 'North Carolina Courage',
            time: 'Today 7:00pm',
            spreadA: '+2.5',
            spreadB: '-2.5',
            moneyLineA: '+220',
            moneyLineB: '-260',
            totalPoints: 'O 160.0 / U 160.0',
            inPlay: false,
        },
        {
            id: 32,
            teamA: 'Houston Dash',
            teamB: 'Chicago Red Stars',
            time: 'Tomorrow 8:30pm',
            spreadA: '-1.0',
            spreadB: '+1.0',
            moneyLineA: '-150',
            moneyLineB: '+130',
            totalPoints: 'O 165.0 / U 165.0',
            inPlay: false,
        },
        {
            id: 33,
            teamA: 'San Diego Wave',
            teamB: 'Seattle Reign',
            time: 'Today 6:00pm',
            spreadA: '+3.0',
            spreadB: '-3.0',
            moneyLineA: '+180',
            moneyLineB: '-220',
            totalPoints: 'O 158.0 / U 158.0',
            inPlay: false,
        },
        {
            id: 34,
            teamA: 'Washington Spirit',
            teamB: 'OL Reign',
            time: 'Tomorrow 9:00pm',
            spreadA: '+4.5',
            spreadB: '-4.5',
            moneyLineA: '+240',
            moneyLineB: '-300',
            totalPoints: 'O 162.0 / U 162.0',
            inPlay: false,
            score: { A: 2, B: 1 },
        },
        {
            id: 35,
            teamA: 'New Jersey Sky Blue',
            teamB: 'Portland Thorns',
            time: 'Today 8:00pm',
            spreadA: '+5.5',
            spreadB: '-5.5',
            moneyLineA: '+200',
            moneyLineB: '-240',
            totalPoints: 'O 170.0 / U 170.0',
            inPlay: false,
        },
        {
            id: 36,
            teamA: 'Orlando Pride',
            teamB: 'North Carolina Courage',
            time: 'Tomorrow 7:00pm',
            spreadA: '+2.5',
            spreadB: '-2.5',
            moneyLineA: '+220',
            moneyLineB: '-260',
            totalPoints: 'O 160.0 / U 160.0',
            inPlay: false,
        },
        {
            id: 37,
            teamA: 'Houston Dash',
            teamB: 'Chicago Red Stars',
            time: 'Today 8:30pm',
            spreadA: '-1.0',
            spreadB: '+1.0',
            moneyLineA: '-150',
            moneyLineB: '+130',
            totalPoints: 'O 165.0 / U 165.0',
            inPlay: false,
            score: { A: 1, B: 1 },
        },
        {
            id: 38,
            teamA: 'San Diego Wave',
            teamB: 'Seattle Reign',
            time: 'Tomorrow 6:00pm',
            spreadA: '+3.0',
            spreadB: '-3.0',
            moneyLineA: '+180',
            moneyLineB: '-220',
            totalPoints: 'O 158.0 / U 158.0',
            inPlay: false,
        },
        {
            id: 39,
            teamA: 'Washington Spirit',
            teamB: 'OL Reign',
            time: 'Today 9:00pm',
            spreadA: '+4.5',
            spreadB: '-4.5',
            moneyLineA: '+240',
            moneyLineB: '-300',
            totalPoints: 'O 162.0 / U 162.0',
            inPlay: false,
            score: { A: 3, B: 2 },
        },
        {
            id: 40,
            teamA: 'New Jersey Sky Blue',
            teamB: 'Portland Thorns',
            time: 'Tomorrow 8:00pm',
            spreadA: '+5.5',
            spreadB: '-5.5',
            moneyLineA: '+200',
            moneyLineB: '-240',
            totalPoints: 'O 170.0 / U 170.0',
            inPlay: false,
        },
        {
            id: 41,
            teamA: 'Atlanta United',
            teamB: 'LA Galaxy',
            time: 'Today 7:00pm',
            spreadA: '+1.5',
            spreadB: '-1.5',
            moneyLineA: '+180',
            moneyLineB: '-220',
            totalPoints: 'O 167.0 / U 167.0',
            inPlay: false,
        },
        {
            id: 42,
            teamA: 'New York City FC',
            teamB: 'FC Dallas',
            time: 'Tomorrow 9:30pm',
            spreadA: '-1.0',
            spreadB: '+1.0',
            moneyLineA: '-135',
            moneyLineB: '+115',
            totalPoints: 'O 164.5 / U 164.5',
            inPlay: false,
        },
        {
            id: 43,
            teamA: 'Toronto FC',
            teamB: 'Vancouver Whitecaps',
            time: 'Today 8:00pm',
            spreadA: '+2.0',
            spreadB: '-2.0',
            moneyLineA: '+200',
            moneyLineB: '-240',
            totalPoints: 'O 160.0 / U 160.0',
            inPlay: false,
        },
        {
            id: 44,
            teamA: 'Seattle Sounders',
            teamB: 'Portland Timbers',
            time: 'Tomorrow 8:00pm',
            spreadA: '+3.5',
            spreadB: '-3.5',
            moneyLineA: '+240',
            moneyLineB: '-300',
            totalPoints: 'O 162.0 / U 162.0',
            inPlay: false,
            score: { A: 2, B: 2 },
        },
        {
            id: 45,
            teamA: 'Los Angeles FC',
            teamB: 'Philadelphia Union',
            time: 'Today 9:00pm',
            spreadA: '-2.5',
            spreadB: '+2.5',
            moneyLineA: '-150',
            moneyLineB: '+130',
            totalPoints: 'O 168.0 / U 168.0',
            inPlay: false,
        },
        {
            id: 46,
            teamA: 'Chicago Fire',
            teamB: 'New England Revolution',
            time: 'Tomorrow 7:00pm',
            spreadA: '+1.0',
            spreadB: '-1.0',
            moneyLineA: '+230',
            moneyLineB: '-270',
            totalPoints: 'O 165.5 / U 165.5',
            inPlay: false,
        },
        {
            id: 47,
            teamA: 'D.C. United',
            teamB: 'Inter Miami',
            time: 'Today 6:30pm',
            spreadA: '+2.0',
            spreadB: '-2.0',
            moneyLineA: '+210',
            moneyLineB: '-250',
            totalPoints: 'O 161.0 / U 161.0',
            inPlay: false,
        },
        {
            id: 48,
            teamA: 'Real Salt Lake',
            teamB: 'San Jose Earthquakes',
            time: 'Tomorrow 8:30pm',
            spreadA: '+4.5',
            spreadB: '-4.5',
            moneyLineA: '+190',
            moneyLineB: '-225',
            totalPoints: 'O 163.0 / U 163.0',
            inPlay: false,
        },
        {
          id: 49,
          teamA: 'Minnesota United',
          teamB: 'Colorado Rapids',
          time: 'Today 7:00pm',
          spreadA: '-1.5',
          spreadB: '+1.5',
          moneyLineA: '-130',
          moneyLineB: '+110',
          totalPoints: 'O 161.0 / U 161.0',
          inPlay: false,
      },
      {
          id: 50,
          teamA: 'Nashville SC',
          teamB: 'Montreal Impact',
          time: 'Tomorrow 8:30pm',
          spreadA: '+2.0',
          spreadB: '-2.0',
          moneyLineA: '+240',
          moneyLineB: '-300',
          totalPoints: 'O 164.0 / U 164.0',
          inPlay: false,
      },
      {
          id: 51,
          teamA: 'FC Cincinnati',
          teamB: 'Atlanta United',
          time: 'Today 6:00pm',
          spreadA: '+3.0',
          spreadB: '-3.0',
          moneyLineA: '+200',
          moneyLineB: '-240',
          totalPoints: 'O 167.0 / U 167.0',
          inPlay: false,
      },
      {
          id: 52,
          teamA: 'Toronto FC',
          teamB: 'Seattle Sounders',
          time: 'Tomorrow 9:00pm',
          spreadA: '+1.0',
          spreadB: '-1.0',
          moneyLineA: '+180',
          moneyLineB: '-220',
          totalPoints: 'O 165.5 / U 165.5',
          inPlay: false,
          score: { A: 3, B: 1 },
      },
      {
          id: 53,
          teamA: 'Philadelphia Union',
          teamB: 'Orlando City',
          time: 'Today 8:00pm',
          spreadA: '-2.5',
          spreadB: '+2.5',
          moneyLineA: '-140',
          moneyLineB: '+120',
          totalPoints: 'O 162.0 / U 162.0',
          inPlay: false,
      },
      {
          id: 54,
          teamA: 'New York Red Bulls',
          teamB: 'Chicago Fire',
          time: 'Tomorrow 7:00pm',
          spreadA: '+0.5',
          spreadB: '-0.5',
          moneyLineA: '+220',
          moneyLineB: '-260',
          totalPoints: 'O 160.0 / U 160.0',
          inPlay: false,
      },
      {
          id: 55,
          teamA: 'Los Angeles FC',
          teamB: 'San Jose Earthquakes',
          time: 'Today 8:30pm',
          spreadA: '-3.0',
          spreadB: '+3.0',
          moneyLineA: '-150',
          moneyLineB: '+130',
          totalPoints: 'O 168.0 / U 168.0',
          inPlay: false,
          score: { A: 4, B: 0 },
      },
      {
          id: 56,
          teamA: 'Real Salt Lake',
          teamB: 'Vancouver Whitecaps',
          time: 'Tomorrow 6:00pm',
          spreadA: '+2.5',
          spreadB: '-2.5',
          moneyLineA: '+200',
          moneyLineB: '-240',
          totalPoints: 'O 163.0 / U 163.0',
          inPlay: false,
      },
      {
          id: 57,
          teamA: 'D.C. United',
          teamB: 'Inter Miami',
          time: 'Today 9:00pm',
          spreadA: '+1.0',
          spreadB: '-1.0',
          moneyLineA: '+210',
          moneyLineB: '-250',
          totalPoints: 'O 161.0 / U 161.0',
          inPlay: false,
          score: { A: 2, B: 2 },
      },
      {
          id: 58,
          teamA: 'Columbus Crew',
          teamB: 'New England Revolution',
          time: 'Tomorrow 8:00pm',
          spreadA: '-2.0',
          spreadB: '+2.0',
          moneyLineA: '-120',
          moneyLineB: '+100',
          totalPoints: 'O 164.5 / U 164.5',
          inPlay: false,
      },
      {
          id: 59,
          teamA: 'FC Dallas',
          teamB: 'Minnesota United',
          time: 'Today 6:30pm',
          spreadA: '-1.5',
          spreadB: '+1.5',
          moneyLineA: '-130',
          moneyLineB: '+110',
          totalPoints: 'O 162.0 / U 162.0',
          inPlay: false,
      },
      {
          id: 60,
          teamA: 'Houston Dynamo',
          teamB: 'Austin FC',
          time: 'Tomorrow 7:00pm',
          spreadA: '+3.0',
          spreadB: '-3.0',
          moneyLineA: '+250',
          moneyLineB: '-300',
          totalPoints: 'O 165.0 / U 165.0',
          inPlay: false,
          score: { A: 1, B: 3 },
      },
      
  ];
  
  const eventListRef = useRef<HTMLDivElement>(null);
  
  useEffect(() => {
    const scrollContainer = eventListRef.current;
    if (!scrollContainer) return;

    const scrollSpeed = 2;


    const scroll = () => {
      scrollContainer.scrollTop += scrollSpeed;

      if (scrollContainer.scrollTop + scrollContainer.clientHeight >= scrollContainer.scrollHeight) {
        scrollContainer.scrollTop = 0;
      }
    };

    const interval = setInterval(scroll, 30);
    return () => clearInterval(interval); 
  }, []);

  return (
<main className="main" style={{ backgroundImage: 'url(/oddsboard-basic-ui/assets/oddsboard.png)' }}>
      <Header title={title} keyMarkets={keyMarkets} />
      <section className="column" ref={eventListRef} style={{ maxHeight: '100vh', overflow: 'auto' }}>
        {events.map((event) => (
          <Event data={event} key={event.id} keyMarkets={keyMarkets} />
        ))}
      </section>
    </main>
  );
}

export default DynamicBoard;